### ISSUE TITLE
华科博士论文最终要提交pdf和word的。

### ISSUE THREAD

**Issue by ShengkaiWu** [XinzeZhang/HUST-PhD-Thesis-Latex#1]
我自己也是用的latex写的论文，但是最终华科的系统里面要提交word版本的博士论文，因此，研究生院要求重新誊写一份word，比较费事，总体上看还不如直接用word写。

**Comment by XinzeZhang** [comment]
是的，不过最终提交系统里(版本时期：2021年6月)，交图书馆的文件是以PDF为准，可以想办法把pdf里面的内容转移到word，比如复制pdf页到word空白页，通过拉伸调节让其覆盖完整的word页面，从而形成一个word文档。

**Comment by XinzeZhang** [comment]
> 我自己也是用的latex写的论文，但是最终华科的系统里面要提交word版本的博士论文，因此，研究生院要求重新誊写一份word，比较费事，总体上看还不如直接用word写。

是的，不过最终提交系统里(版本时期：2021年6月)，交图书馆的文件是以PDF为准，可以想办法把pdf里面的内容转移到word，比如复制pdf页到word空白页，通过拉伸调节让其覆盖完整的word页面，从而形成一个word文档。

**Comment by RainerTian** [comment]
这个应该可以用pandoc来转换成.docx
