### ISSUE TITLE
关于参考文献格式的问题

### ISSUE THREAD

**Issue by walcheng** [XinzeZhang/HUST-PhD-Thesis-Latex#12]
您好，现在最新的会议参考文献要求把以前的“in”换成"In"，同时年份后面跟":"而不是现在的"."，想请问这些怎么修改，太感谢了
![截屏2024-01-23 09 38 38](https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/40264048/7668980d-aebf-461a-bea1-d5d85fb8b9f5)

**Comment by XinzeZhang** [comment]
<img width="495" alt="B1B1A232-8EA0-4B9E-A7F2-5C418C8B7F15" src="https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/17476403/54191783-8b64-4e7d-a861-b1f91c2ff0aa">
在我的bst文件定下，出版年后跟的是冒号

**Comment by walcheng** [comment]
好的，'in'的问题也已经解决，十分感谢

**Comment by walcheng** [comment]
学长，我刚刚直接复制你的 bst 文件，发现仍然是句号，不知道学长用的哪个版本
![截屏2024-01-24 09 16 47](https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/40264048/62947564-52f0-43bb-a862-b6ddb609f83a)
