### ISSUE TITLE
最新版无法加载图片问题

### ISSUE THREAD

**Issue by walcheng** [XinzeZhang/HUST-PhD-Thesis-Latex#14]
![截屏2024-02-18 14 23 52](https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/40264048/6da80729-746c-459b-a0ba-c2654fe2ba8f)
最新版本无法加载图片，overleaf 和 vscode 都是一样的问题，请问如何解决，谢谢！

**Comment by XinzeZhang** [comment]
<img width="607" alt="image" src="https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/17476403/2078edc0-d6b0-4ff5-90e8-2257fdb41a4d">

您好。当前版本在本地编译的过程中，没有此问题。可能是你在main.tex文件的documentclass[*]中添加了draft。

**Comment by XinzeZhang** [comment]
> ![截屏2024-02-18 14 23 52](https://private-user-images.githubusercontent.com/40264048/305689096-6da80729-746c-459b-a0ba-c2654fe2ba8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzg0MTIsIm5iZiI6MTcwODIzODExMiwicGF0aCI6Ii80MDI2NDA0OC8zMDU2ODkwOTYtNmRhODA3MjktNzQ2Yy00NTliLWEwYmEtYzI2NTRmZTJiYThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZThiZTQxMjA1ZTU0MzRiMWE0YmIzMjc2OTVjNWYyNGE5Y2I4MjAwNTNkYjJjOTRiMTFjNWRhMzdhNWYyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jE-qeOeX83BLJHGInHAHuafXaECJMCCrdjcZVWHE_RM) 最新版本无法加载图片，overleaf 和 vscode 都是一样的问题，请问如何解决，谢谢！

<img width="607" alt="image" src="https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/17476403/2078edc0-d6b0-4ff5-90e8-2257fdb41a4d">

@walcheng  您好。当前版本在本地编译的过程中，没有此问题。可能是你在main.tex文件的documentclass[*]中添加了draft。

**Comment by walcheng** [comment]
是的，确实是在main.tex文件的documentclass[*]中添加了draft导致的，现在能够正常显示了，谢谢！
