### ISSUE TITLE
有何注意事项？

### ISSUE THREAD

**Issue by Shalom-Chaver** [XinzeZhang/HUST-PhD-Thesis-Latex#2]
师兄您好，我预计2022年毕业，刚下载好华科latex模板。之前用爱思唯尔模板写过论文，用这个新模板还是有一点疑问，比如积分符号\int是不是直接使用就可以？各类数学符号的使用和平常用法是不是相同呢？另一个问题是，图、表和公式的交叉引用命令分别是啥呀？我平日里用的方式是定义了新命令，
\newcommand{\Figref}[1]{Fig.~\ref{#1}}
\newcommand{\eqsref}[1]{Eq.~\eqref{#1}}
\newcommand{\tableref}[1]{Table.~\ref{#1}}
中间的那个～是确保在引用中间不分行，比如Fig. 1，在Fig和1之间不会分行，现在用新模板，不确定有没有更好的方法去实现交叉引用。
求师兄帮忙解惑，或者，有没有一个模板的使用注意事项呢？谢谢师兄。

**Comment by Shalom-Chaver** [comment]
另一个问题是，我插入一个公式，公式编号默认是（式1.1），没什么办法可以改成（1-1）呐？

**Comment by Shalom-Chaver** [comment]
我只能把（式1.1）改为（式1-1），有什么办法去掉那个“式”字？？？跪求大神。。。

**Comment by Shalom-Chaver** [comment]
> 师兄您好，我预计2022年毕业，刚下载好华科latex模板。之前用爱思唯尔模板写过论文，用这个新模板还是有一点疑问，比如积分符号\int是不是直接使用就可以？各类数学符号的使用和平常用法是不是相同呢？另一个问题是，图、表和公式的交叉引用命令分别是啥呀？我平日里用的方式是定义了新命令， \newcommand{\Figref}[1]{Fig.~\ref{#1}} \newcommand{\eqsref}[1]{Eq.~\eqref{#1}} \newcommand{\tableref}[1]{Table.~\ref{#1}} 中间的那个～是确保在引用中间不分行，比如Fig. 1，在Fig和1之间不会分行，现在用新模板，不确定有没有更好的方法去实现交叉引用。 求师兄帮忙解惑，或者，有没有一个模板的使用注意事项呢？谢谢师兄。

**Comment by XinzeZhang** [comment]
数学符号的使用方法是与一般的latex环境保持相同的。
图、表和公式的交叉应用命令可用如`图~\ref{fig:figname}`的形式进行交叉应用。
这种模板一般没有特别的注意事项，和latex环境需要注意的地方没有较大差别。
