### ISSUE TITLE
请问如何设置为人文社科类的博士论文？脚注用带圈的数字编号，引用采用括号内作者加年号。

### ISSUE THREAD

**Issue by hustquick** [XinzeZhang/HUST-PhD-Thesis-Latex#21]
[人文社科-博士-华中科技大学学位论文参考模板.docx](https://github.com/user-attachments/files/15966969/-.-.docx)
对于人文社科类博士，其格式有所区别。

上面给出了人文社科博士学位论文的参考模板，请参考。

这里是从万方上下载的一篇博士论文的样例。

<img width="1415" alt="image" src="https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/12826825/b5b07897-c576-40d0-86f9-03172669a99b">
请问，该如何修改 cls 文件，才能得到这样的格式输出。

**Comment by XinzeZhang** [comment]
脚注该起来问题不大。但，在现在模版基础上增加author year格式的引用，难度和工作量是比较大的。

这个功能最早等8月底之后才可能有时间来做一下。


Sincerely，

Xinze Zhang
------
Ph.D Candidate,
John Hopcroft Lab,
School of Computer & Science,
Huazhong University of Science & Technology

在 2024年6月25日，下午3:57，张成 ***@***.***> 写道：

﻿

人文社科-博士-华中科技大学学位论文参考模板.docx<https://github.com/user-attachments/files/15966969/-.-.docx>
对于人文社科类博士，其格式有所区别。

上面给出了人文社科博士学位论文的参考模板，请参考。

这里是从万方上下载的一篇博士论文的样例。

image.png (view on web)<https://github.com/XinzeZhang/HUST-PhD-Thesis-Latex/assets/12826825/b5b07897-c576-40d0-86f9-03172669a99b> 请问，该如何修改 cls 文件，才能得到这样的格式输出。

**Comment by hustquick** [comment]
谢谢。
