### ISSUE TITLE
参考文献引用问题

### ISSUE THREAD

**Issue by Cynthia-XinyuWang** [XinzeZhang/HUST-PhD-Thesis-Latex#23]
求问大佬，目前参考文献引用会出现上标，但是学校的word文件里面貌似没有这个，请问这个会被教务说么，还是会有什么其他的解决办法

**Comment by XinzeZhang** [comment]
能否给出图例？

Sincerely，

Xinze Zhang
------
Post Doc.,
School of Computer & Science,
Huazhong University of Science & Technology

在 2024年10月24日，中午12:07，Cynthia Wang ***@***.***> 写道：

﻿

求问大佬，目前参考文献引用会出现上标，但是学校的word文件里面貌似没有这个，请问这个会被教务说么，还是会有什么其他的解决办法

**Comment by Cynthia-XinyuWang** [comment]
![85221729740550_ pic](https://github.com/user-attachments/assets/4a87ff59-3ae8-45a1-a33a-67b8673c9afe)
谢谢大佬回复，我的意思是指如果我要引用一个论文，他这里会出现上标，比如图中的[1]，但是学校的文件里面这个上标是被允许的么，有点担心到时候教务会指出这个问题，要求修改

**Comment by XinzeZhang** [comment]
您好 年代法和数字法只使用一种，你的这种属于混用，是不符合规范的。

建议只保留数字。这种数字上角标在我看来是合规的。也有很多同学使用此模版提交了论文。


Sincerely，

Xinze Zhang
------
Post Doc.,
School of Computer & Science,
Huazhong University of Science & Technology

在 2024年10月24日，中午12:20，Cynthia Wang ***@***.***> 写道：

﻿

85221729740550_.pic.jpg (view on web)<https://github.com/user-attachments/assets/4a87ff59-3ae8-45a1-a33a-67b8673c9afe>
谢谢大佬回复，我的意思是指如果我要引用一个论文，他这里会出现上标，比如图中的[1]，但是学校的文件里面这个上标是被允许的么，有点担心到时候教务会指出这个问题，要求修改
