### ISSUE TITLE
章标题行距问题

### ISSUE THREAD

**Issue by Xiong5Heng** [XinzeZhang/HUST-PhD-Thesis-Latex#24]
我在word模板里看到章标题为1.5倍行距，但学院给的以及您最新的latex模板是1倍行距

这是word模板
![image](https://github.com/user-attachments/assets/9bad7cb3-b114-4a34-a653-0f6298d8f58f)

这是latex模板
![image](https://github.com/user-attachments/assets/766eb528-f990-4391-a8e1-62c76c21cd17)

**Comment by XinzeZhang** [comment]
这个学校的文件里面似乎没有明细要求，可以根据学院的模板和当前模板的pdf版本，比对差异是否明显，如果明显可以自行调整一下。
