### ISSUE TITLE
可以用latex写毕业论文嘛

### ISSUE THREAD

**Issue by JOOSUKE** [XinzeZhang/HUST-PhD-Thesis-Latex#26]
请问机械学院硕士允许使用latex写毕业论文嘛

**Comment by XinzeZhang** [comment]
这个需要跟学院确认。主要还是看学位系统是否能上传latex版本的源文件。
Sincerely，

Xinze Zhang
------
Post Doc.,
School of Computer & Science,
Huazhong University of Science & Technology

在 2024年11月29日，下午5:14，JOOSUKE ***@***.***> 写道：

﻿

请问机械学院硕士允许使用latex写毕业论文嘛

**Comment by JOOSUKE** [comment]
好的 感谢解答
