### ISSUE TITLE
Something's wrong--perhaps a missing \item

### ISSUE THREAD

**Issue by Shalom-Chaver** [XinzeZhang/HUST-PhD-Thesis-Latex#3]
模板总体用着非常顺畅，格式设定得特别好，唯一一个问题是，我没有改动之前的附录文件如：publications、patent、project，但是每次编译都显示Something's wrong--perhaps a missing \item，我只能把这些附录文件注释掉，不编译。不知道有没有什么办法解决这个问题。。。

**Comment by XinzeZhang** [comment]
不好意思，最近比较忙，争取下次更新的时候解决这个问题。

**Comment by RainerTian** [comment]
Configuration file subfig.cfg not found，还有这个，不知道有没有办法解决？

**Comment by XinzeZhang** [comment]
您好

这个问题可能是subfig宏包导致的，可以换成subcaption试试。

Sincerely，

Xinze Zhang
------
Ph.D Candidate,
John Hopcroft Lab,
School of Computer & Science,
Huazhong University of Science & Technology

在 2022年11月6日，21:03，RainerTian ***@***.***> 写道：

﻿

Configuration file subfig.cfg not found，还有这个，不知道有没有办法解决？

**Comment by RainerTian** [comment]
感谢您的回复，其实目前我不需要子图的排列，我会在PPT里把图组好。这个问题不知道在您那边有没有提示，还是我软件安装的问题，我是使用的LeXStudio2022,目前只是Warning,好像还没有导致报错，您说的subcaption应该是\usepackage{subfig}包吧，加载后仍然会显示，截图给您看一下，
![微信截图_20221107093646](https://user-images.githubusercontent.com/101238142/200209125-4c903762-f953-44c3-80a6-3152f331f68d.png)​目前还有一个问题，不知道是哪里我输入错误导致参考文献序号都变成了？，文末也没有了参考文献那章，麻烦您看一下，谢谢

**Comment by XinzeZhang** [comment]
warning 一般不用管， subfig宏包比subcaption老，在新版本下容易出现问题，不需要子图排列的，可以试试吧subfig宏包的载入都注释掉；
参考文献序号问题，是一果多因的问题，可能是在执行tex编译命令的时候，少了一个xetex，以vscode上的编译命令为例，完整的编译命令应该是：xelatex，xelatex，biblatex，xelatex。此问题可参考刘海洋老师著的《latex 入门》

**Comment by RainerTian** [comment]
好的，谢谢回复
