### ISSUE TITLE
xeCJKfntef.sty: 错误: 173: Missing \begin{document}. \xeCJK_declare_node:n { u

### ISSUE THREAD

**Issue by GeorgeCarpenter** [XinzeZhang/HUST-PhD-Thesis-Latex#30]
怎么解决？

**Comment by GeorgeCarpenter** [comment]
github repo下载下来跑报错，文件完全没改

**Comment by XinzeZhang** [comment]
建议在提问前，先自己Google一下，相似的问题和解决方法可以参考：https://github.com/Haixing-Hu/nju-thesis/issues/33。可能是你安装的tex版本不对。已发布的文件，是可以在overleaf，或者本地用vscode打开正常编译的。

另外， 请注意提问语气。

> github repo下载下来跑报错，文件完全没改

**Comment by GeorgeCarpenter** [comment]
应安装什么版本的tex?

**Comment by GeorgeCarpenter** [comment]
能否在主页README中提供下载链接？

**Comment by GeorgeCarpenter** [comment]
overleaf显示文件太大，上传不上去？

**Comment by XinzeZhang** [comment]
> 应安装什么版本的tex?

texlive的最新版就可以，可以直接在华科镜像站，https://mirrors.hust.edu.cn/CTAN/systems/texlive/Images/， readme已更新。

**Comment by XinzeZhang** [comment]
> overleaf显示文件太大，上传不上去？

可以分件传
