### ISSUE TITLE
如何在独创性申明里放电子签名啊？

### ISSUE THREAD

**Issue by reresearcher** [XinzeZhang/HUST-PhD-Thesis-Latex#9]

**Comment by XinzeZhang** [comment]
可以在最终生成的pdf文件里面，用pdf编辑工具，例如Adobe放置电子签名，或者单独用word或者其他工具生成一个单独的独创性声明页（该页也是学位系统里必须单独提交的项目）将最终生成的pdf文件的独创性声明页进行替换。

**Comment by reresearcher** [comment]
感谢！
